name: Combine PRs

on:
  workflow_dispatch:

jobs:
  combine-prs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
